// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(RecipeDbContext))]
    [Migration("20240302210408_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.16");

            modelBuilder.Entity("RecipeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is the description for sample entity 1.",
                            Image = "https://example.com/image1.jpg",
                            Title = "Sample Title 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description for sample entity 2.",
                            Image = "https://example.com/image2.jpg",
                            Title = "Sample Title 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Yet another description.",
                            Image = "https://example.com/image3.jpg",
                            Title = "Another Title"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description for entity with Id 4.",
                            Image = "https://example.com/image4.jpg",
                            Title = "Title 4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description for the fifth entity.",
                            Image = "https://example.com/image5.jpg",
                            Title = "Fifth Entity"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
